### ISSUE TITLE
3.0.0-nightly: Token Simulation doesn't turn off

### ISSUE THREAD

**Issue by falko** [bpmn-io/bpmn-js-token-simulation-plugin#15]
In today's nightly build of Camunda Modeler 3.0.0 the Token Simulation does not turn off using its button keyboard shortcut. That leaves the current models tab unusable and unsaved changes are lost.

**Comment by pinussilvestrus** [comment]
Hi @falko, can you give some more information about the steps you did to reproduce it? I was not able to do so on macOS and Windows with the [latest nightly](https://camunda.org/release/camunda-modeler/nightly/). By pressing 'T' it is possible to turn the simulation off.

**Comment by nikku** [comment]
@pinussilvestrus This may be a Linux / Windows related thing. 

I'll have a look and check whether our latest improvements fix the issue on Linux.
