### ISSUE TITLE
Unable to see which outgoing sequence flow of an exclusive gateway is selected

### ISSUE THREAD

**Issue by ingorichtsmeier** [bpmn-io/bpmn-js-token-simulation-plugin#18]
__Describe the Bug__

After updating to the latest version (0.10.0) of this plugin, I can't see which outgoing sequence flow of an exclusive gateway is selected. All sequence flows are painted black.

![image](https://user-images.githubusercontent.com/9433996/99071447-6db64400-25b2-11eb-87ca-1ec989fc7b5f.png)

In the former version, only the selected flow was black and the other ones were painted grey.

__Steps to Reproduce__

1. Install version 0.10.0 of the token simulation plugin in Camunda Modeler 4.3.0
2. Model a process with an exclusive gateway and at least two outgiong sequence flows.
3. enable the simulation. All sequence flows keep black. The token simulation works.

__Expected Behavior__

Only the selected flow is painted black, the other flows appear lighter grey.

![image](https://user-images.githubusercontent.com/9433996/99071514-93434d80-25b2-11eb-9b73-9a8e88b2f12f.png)

__Environment__

- Host Camunda Modeler 4.3.0
- OS: Windows 10
- Library version: 0.10.0

**Comment by nikku** [comment]
This is likely due to the diagram coloring introduced with `bpmn-js@7.3`.

**Comment by Do-min-ik** [comment]
The problem is actually that `css/bpmn-js-token-simulation.css ` is too old and misses the "--token-simulation-*" properties.

See my fork for a fix: https://github.com/Do-min-ik/bpmn-js-token-simulation-plugin

**Comment by Do-min-ik** [comment]
I'm going to provide a PR either tonight or in the couple of days.

**Comment by pinussilvestrus** [comment]
That is great @Do-min-ik ! Looking forward 👍

**Comment by nikku** [comment]
Fixed with `v0.10.1` of the plug-in.

**Comment by ingorichtsmeier** [comment]
Cool, works very well! 👍
