### ISSUE TITLE
Provide support for more elements and skip documentation elements

### ISSUE THREAD

**Issue by Guchman** [bpmn-io/bpmn-js-token-simulation-plugin#21]
Hi, great plugin, thanks,
but it's seems to be not very usable on realworld schemas, because a lack of support of some elements. It's fails on documentation elements like message flows either. 

I have intermediate events for status tracking on scheme which is very basic one and get error messages about unsupported elements.
It contains message flow elements which is no supported ether, but flow elements uses only for documentation purposes 
and could be omitted by token emulation.

**Comment by nikku** [comment]
Thanks for your feedback.

Please open concrete issues for individual cases using our [existing issue templates](https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/new/choose).

We'd need the full context, including an example diagram to act upon your request.
