### ISSUE TITLE
Message flow support

### ISSUE THREAD

**Issue by Guchman** [bpmn-io/bpmn-js-token-simulation-plugin#22]
Token Simulation fails due to Message Flow is unsupported element.

Please, support message flow in your plugin. It's exists only for documentation purpose  in Camunda, so your plugin should just skip it.

![image](https://user-images.githubusercontent.com/10250050/101365853-59195300-38b5-11eb-8ac8-a23a146316c8.png)

**Comment by nikku** [comment]
Fixed upstream via https://github.com/bpmn-io/bpmn-js-token-simulation/pull/52.
