### ISSUE TITLE
Generic ThrowEvent support

### ISSUE THREAD

**Issue by Guchman** [bpmn-io/bpmn-js-token-simulation-plugin#23]
Throw events is not supported now so simulation fails.

Please, add support, it's do the same thing as any service task from tokens perspective, so it's should not be a problem

![image](https://user-images.githubusercontent.com/10250050/101366324-e0ff5d00-38b5-11eb-9cb4-bfe357f10a38.png)

**Comment by nikku** [comment]
Fixed via https://github.com/bpmn-io/bpmn-js-token-simulation/pull/53.
