### ISSUE TITLE
Provide support for ReceiveMessageTask

### ISSUE THREAD

**Issue by Guchman** [bpmn-io/bpmn-js-token-simulation-plugin#24]
Token simulation fails on message receive task.

Please provide support, it's shouldn't be a problem, cause you're already have support for ThrowMessageEvent

![image](https://user-images.githubusercontent.com/10250050/101366748-6420b300-38b6-11eb-881f-af58266b0f49.png)

**Comment by nikku** [comment]
> Please provide support, it's shouldn't be a problem, cause you're already have support for ThrowMessageEvent

Throw and receive in theory have different semantics. So I could see us implementing receive in a way that simulates an incoming message, too.

**Comment by Guchman** [comment]
Sorry, my mistake. I've meant receive-message-event

**Comment by nikku** [comment]
Both have very similar semantics and should not work any different than a `conditional catch event`:

![image](https://user-images.githubusercontent.com/58601/101939781-c135a500-3be5-11eb-882d-da10e14ddf65.png)

Feel free to PR a change that adds supports for the elements.
