### ISSUE TITLE
Pausing of token disabled if process is modeled inside process pool

### ISSUE THREAD

**Issue by timstawowski** [bpmn-io/bpmn-js-token-simulation-plugin#29]
__Describe the Bug__

When I try to pause a running token simulation, the pause button is disabled if a process is modeled inside a pool element.

__Steps to Reproduce__

1. Model simple process
2. Wrap a bpm pool element around
3. Start token simulation
4. Try to use the "pause" button

__Expected Behavior__

The pause button should function the same way as it does without a pool element.

__Environment__

- Modeler: 4.7.0
- OS: [Ubuntu 20.04.2 LTS]

![bug_pausing_token_inside_pool](https://user-images.githubusercontent.com/46934301/116068822-f3264000-a68a-11eb-91a4-bc64863d6d8c.gif)

**Comment by nikku** [comment]
This is fixed upstream with the latest version of [bpmn-js-token-simulation](https://github.com/bpmn-io/bpmn-js-token-simulation).
