### ISSUE TITLE
Play-Button is not reactivated after simulation finishes in multi pool models

### ISSUE THREAD

**Issue by FO-e-X** [bpmn-io/bpmn-js-token-simulation-plugin#30]
__Describe the Bug__
When a BPMN contains not only multiple lanes in a single pool, even if there are multiple pools with 1 or more lanes, each process start event has a "play button". When I choose one of the events to run the simulation, it all runs fine (in the newest version with a lot more supported elements (y) ). After the simulation run is over, in nearly all scenarios of model designs all start events get back their play button. But if you have 2 or more pools in a model, only the play button of the started pool reapears. I need to shut down token simulation an start it again, then all start events are runnable again. This is what I expect after finishing too.

__Steps to Reproduce__
1.) create a new pool
2.) add a simple process to simulate in pool 1
3.) create another new pool
4.) add a simple process to simulate again in pool 2
5.) run simulation in any pool
6.) after finishing of simulation 1 try to start to simulate the other one ;)

__Expected Behavior__
I expect the same behavior like at the beginning, when i activate the plugin and set Token Simulation to green. Then all pools can be simulated.

__Environment__
Modeler 4.7.0 win-x64

Best regards
Frank

**Comment by nikku** [comment]
This is fixed upstream with the latest version of [bpmn-js-token-simulation](https://github.com/bpmn-io/bpmn-js-token-simulation).
