### ISSUE TITLE
switch at gateway does not show other pathes in grey

### ISSUE THREAD

**Issue by germans-code** [bpmn-io/bpmn-js-token-simulation-plugin#31]
This on 4.8.1.8069 on OS X 10.15.7

Switching at the gateway shows no difference and the choosen path looks like the others.

<img width="751" alt="Bildschirmfoto 2021-05-19 um 18 43 25" src="https://user-images.githubusercontent.com/82450645/118851505-1fbc2900-b8d2-11eb-8f94-3d090fce9d19.png">

---

Depends on https://github.com/camunda/camunda-modeler/pull/2281.

**Comment by nikku** [comment]
This is fixed upstream with the latest version of [bpmn-js-token-simulation](https://github.com/bpmn-io/bpmn-js-token-simulation).

**Comment by germans-code** [comment]
Nice, but not at the *copy-to-plugin-folder-version*. (https://github.com/bpmn-io/bpmn-js-token-simulation-plugin)
I've no Idea how to use the *Install-version*.

**Comment by nikku** [comment]
Fixed upstream means we need to integrate these upstream fixes into the release. Fixed (and this issue closed) means that the plug-in is fixed.

**Comment by nikku** [comment]
Will be fixed in next Camunda Modeler release.
