### ISSUE TITLE
The plugin does not create optional token for Boundary Message event (non-interrupting)

### ISSUE THREAD

**Issue by vatsekov** [bpmn-io/bpmn-js-token-simulation-plugin#34]
__Describe the Bug__

The plugin does not create optional token for Boundary Message event (non-interrupting)

Create a diagram containing Boundary Message event (non-interrupting)
![image](https://user-images.githubusercontent.com/80213649/121824989-a210f080-ccb8-11eb-98d9-9602d3530d28.png)

__Expected Behavior__

There should be a possibility to create a new token for the message boundary event

__Environment__

Windows 10
Camunda modeler 4.8.1

**Comment by nikku** [comment]
Hi @vatsekov. 

Obviously you can only trigger a non-interrupting boundary message event the moment the task is active. The user task, as it stands is simply passed through and thus is not _active_ so you as a user can trigger the boundary event. Not sure what you do expect in your scenario.

Check the receive task which has waiting (receive) semantics:

![capture YdcOGj_optimized](https://user-images.githubusercontent.com/58601/121847440-dd2b1800-cce8-11eb-8071-da6f9d7cdb75.gif)

**Comment by vatsekov** [comment]
Hi @nikku 
But why the User task is simply passed through? The Camunda engine waits for its completion before the process continues (unlike the Manual task, which is is handled as a pass-through activity). There could be multiple tokens triggered on the optional path of the boundary event, while the engine waits for the User task completion.
Shouldn't the Simulation wait for user click before processing the User task, instead of treating it as a pass through?

Thank you

**Comment by nikku** [comment]
I believe what you expect is https://github.com/bpmn-io/bpmn-js-token-simulation/issues/9, right?

The token simulation tool is not meant to 1:1 simulate async boundaries / wait states the engine supports. Instead, it is meant to teach people about the token flow. Thus you'll see some differences between the simulator and the engine.

**Comment by vatsekov** [comment]
yes, I think it would be a logical behavior for the User task.
Thank you
