### ISSUE TITLE
Behaviour on synchronous communication

### ISSUE THREAD

**Issue by jonathanlukas** [bpmn-io/bpmn-js-token-simulation-plugin#42]
__Describe the Bug__

When modelling synchronous communication, the behaviour is not as expected. On arriving at the task, the token will wait. On continuing, the message is sent and the token continues, ignoring the returning message flow.

You will find the behaviour in the attached video.
https://user-images.githubusercontent.com/81753891/143849238-c353b166-5ef7-4808-8923-0aa35c3cd0d7.mov

__Steps to Reproduce__

1. Model two processes in one diagram.
2. Draw one step that communicates synchronous with the other process
3. The token will be stuck at this point, see video

__Expected Behavior__

I would assume that on arriving at the synchronous communication task, the send message will be done. After this, the token will wait for the returning message and continue on arrival of this message.

Generally speaking (cf. https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/42#issuecomment-981560928, https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/42#issuecomment-981589407) message flows shall execute in diagram direction (left-to-right). 

__Environment__

- Host (Browser/Node version), if applicable: Camunda Modeler, version 4.11.1
- OS: MacOS Big Sur 11.6.1
- Library version: 0.13.1

**Comment by nikku** [comment]
Thanks for opening this bug report.

The case you present is a _very_ interesting one, especially due to the fact that message flows do not have execution semantics in theory. In practice, of course, we do see that people follow along message flows to understand the way complex collaborations interact, hence we implement message flow behavior, too.

What is especially interesting about multiple incoming / outgoing message flows being attached to a node is whether we can derive some execution semantic based on the visual representation. Let me try to test this with you. Given the following diagram, what would you expect to happen on activation of each task, and task continuation / signal after a message receive:

![image](https://user-images.githubusercontent.com/58601/143862797-b5abefec-5e16-447c-91f0-0d943f0ea0c4.png)

**Comment by jonathanlukas** [comment]
Thank you for your quick reaction. Given the process diagram above, I would expect the following behaviour:
1. Task A started, sends message, waits for response
2. Task C started, sends message, continues to D
3. Task D started, waits for message
3. Task A ended after message caught continues
4. Task B started, sends message
5. Task D receives message, sends response, waits for another message
6. Task B receives message, sends another message, continues
7. Task D receives another message, continues

The general assumption is that the message flows are read in modelling direction (from left to right in Camundas case). 

If the next message flow is sending, a message will be sent. This message flow has then to be marked as "handled" or something similar.

If the next message flow is receiving, a wait state is entered. I love the behaviour of the token simulation plugin here :) After a message is received, also this receiving message flow has to be marked as "handled".

From BPMN 2.0 standard perspective, there are initial messages and response messages, there are event message objects (with white and grey letter symbols). Implementing this would maybe take it a bit too far...

I hope this is a good clarification of what I would expect from a messaging behaviour simulation.

**Comment by nikku** [comment]
> The general assumption is that the message flows are read in modelling direction (from left to right in Camundas case).

I did not want to spoil anything, but this is exactly what I had in mind, too. 

Thanks for your feedback. A valuable improvement of our message flow simulation semantics. Ready to be picked up, once we find the time.

Also, consider contributing, if you can :).

**Comment by nikku** [comment]
What about this?


![capture e9QiMP_optimized](https://user-images.githubusercontent.com/58601/143930128-89abaf17-d0c2-44a2-8fa0-408a765350c9.gif)

**Comment by nikku** [comment]
Me too, :heart:
