### ISSUE TITLE
Menu Plugin Included in Camunda Cloud BPMN Tab

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/bpmn-js-token-simulation-plugin#48]
__Describe the Bug__

Even though Camunda Cloud BPMN plugins aren't supported the [menu](https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/blob/master/index.js#L7) and [style](https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/blob/master/index.js#L6) plugins are included regardless. When using the menu plugin there is an error since the bpmn-js plugin wasn't included.

![wbs4j4rVJN](https://user-images.githubusercontent.com/7633572/152166268-7c38b218-70a3-46ad-b684-ba778d5bfda5.gif)

This isn't necessarily a bug but could also require a fix in the Camunda Modeler.

__Steps to Reproduce__

1. Install plugin
2. Create Camunda Cloud BPMN tab
3. Use menu plugin
4. Error in log

__Expected Behavior__

Menu plugin not included if Camunda Cloud BPMN tab.

__Environment__

- Library version: 0.15.0

**Comment by Skaiir** [comment]
Hello hello, this is something which we saw as part of the plugins investigations I was doing and will be handled as part of the changes outlined here: https://github.com/bpmn-io/internal-docs/issues/425.

I shall hence annex this issue.

**Comment by philippfromme** [comment]
@Skaiir Great to hear!

**Comment by Skaiir** [comment]
Depends on https://github.com/camunda/camunda-modeler/issues/2757
